# Numpy basics

In this notebook the goal is to get comfortable with the basics of numpy, such as defining vectors, matrices, higher-order tensors and basic operations like, multiplication, transposition, matrix inverse, matrix determinants, eigenvalues and eigen vectors and SVD.

For more resources please see: (https://numpy.org/doc/stable/user/absolute_beginners.html)

### Array creation

```
There are 6 general mechanisms for creating arrays:

Conversion from other Python structures (i.e. lists and tuples)

Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

Replicating, joining, or mutating existing arrays

Reading arrays from disk, either from standard or custom formats

Creating arrays from raw bytes through the use of strings or buffers

Use of special library functions (e.g., random)

In [ ]:
import numpy as np

In [ ]:
# create a 1D array from a python list
a1D = np.array([1, 2, 3, 4])
# create a 2D array from a python list of lists
a2D = np.array([[1, 2], [3, 4]])
# create a 3D array from a python list of list of lists
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# lets print the shape of each array
print(a1D.shape) # shape (4,) is a vector of 4 values
print(a2D.shape) # shape (2, 2) is a 2x2 matrix
print(a3D.shape) # shape (2,2,2) is a 3-dimensional tensor

In [ ]:
#we can specify the dtype of an array
print(np.array([127, 128, 129], dtype=np.int8)) # 8 bit signed integer - this will give a warning !!!
print(np.array([127, 128, 129], dtype=np.int64)) # 64 bit signed integer
print(np.array([5, 6, 7], dtype=np.uint32)) # 32 bit unsigned integer
print(np.array([127, 128, 129], dtype=np.float32)) # normal floating point precision
print(np.array([127, 128, 129], dtype=np.float16)) # lower floating point precision
print(np.array([127, 128, 129], dtype=np.float64)) # higher floating point precision

In [ ]:
# 1D numpy array creation functions similar to python range 
print(np.arange(10))
#array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.arange(2, 10, dtype=float))
#array([2., 3., 4., 5., 6., 7., 8., 9.])
print(np.arange(2, 3, 0.1))
#array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
# 2D numpy array creation functions
# Create the 3x3 Identity matrix
print(np.eye(3))
# Create the 3x5 Identity matrix
print(np.eye(3, 5))
# Create a diagonal matrix from a vector
print(np.diag([1, 2, 3]))
# Create an off diagonmal matrix from a vector
print(np.diag([1, 2, 3], 1))
# From a matrix np.diag returns the diagonal vector
a = np.array([[1, 2], [3, 4]])
print(np.diag(a))

In [ ]:
# general numpy array creation functions
# create a 2x3 matrix filled with zeros
print(np.zeros((2, 3)))
# create a 2x3 matrix filled with ones
print(np.ones((2, 3)))
# create a higher-order tensor filled with 0.5s
print(np.zeros((2,3,3,5))+0.5)

In [ ]:
# generating random numpy array with np.random
import numpy.random as nr
# create a vector of random numbers sampled uniformly from [0, 1]
print(nr.random(10))
# create a matrix of random numbers sampled uniformly from [0, 1]
print(nr.random((4,4)))
# create a vector of random numbers sampled from the standard normal distribtution
print(nr.randn(10))
# create a matrix of random numbers sampled from the standard normal distribtution
print(nr.randn(4,4))

### Array indexing and slicing

Just like lists and strings in python we can index and slice numpy arrays in a similar way.

In [ ]:
x = np.arange(10)
print(x)
print(x[2])
print(x[-2])

In [ ]:
# make x 2-dimensional with reshape
x = x.reshape(2, 5) # 2 * 5 = 10 so this works 
print(x)
x = x.flatten() # flatten x so it is a vector again
print(x)
x = x.reshape(5, -1) # reshape x so its first dimension is 5 and the remaining dimension is 10/5
print(x)

In [ ]:
# we can index our reshaped x array
print(x)
print(x[2, 1]) # print the value at row 2 and column 1

In [ ]:
# let's redefine x
x = np.arange(10)
print(x)
# lets slice x
print(x[1:5]) # get elements from 1 to 4 (inclusive)
print(x[1:7:2]) # get elements from 1 to 7 (skipping over every other value)
print(x[-2:10]) # get elements from the second last to 9 (inclsuive) 
print(x[-3:3:-1]) # get elements from the third last to the third (going down -1)
print(x[5:]) # gete elements from the fifth onwards

In [ ]:
# weird shapes
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(x)
print(x.shape)

In [ ]:
x = np.arange(4*3*2).reshape(4,3,2)
print(x)
# using ellipses indexing
print(x[..., 0]) 
# this is equivalent to
print(x[:, :, 0]) # we want all values on the first dimension all in the second dimension and only 0 in the third dimension
print(x[0, 0:2, 0])

In [ ]:
# we can add dimensions to a numpy array in two different ways
x = np.arange(4*3*2).reshape(4,3,2)
print(x.shape)
print(x[:, np.newaxis, :, :].shape)
print(x[:, None, :, :].shape)


In [ ]:
# something weird
x = np.arange(5)
print(x)
print(x[:, np.newaxis] + x[np.newaxis, :])

In [ ]:
# we can index with arrays
x = np.arange(10, 1, -1)
print(x)
indices = np.array([3, 3, 1, 8])
print(x[indices])

In [ ]:
# we can do the same with higher-order numpy array
y = np.arange(35).reshape(5, 7)
print(y)
print(y[np.array([0, 2, 4]), np.array([0, 1, 2])])

In [ ]:
# similarly 
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)

print(x[rows, columns])

In [ ]:
# boolean array indexing
# we can index numpy array based on a boolean mapping
x = np.arange(35).reshape(5, 7)
print(x)
b = x > 20
print(b) # print the boolean mask
print(x[b])

In [ ]:
# we can do this to remove nan values
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
print(x[~np.isnan(x)])

In [ ]:
# other funky things we can do
x = np.array([1., -1., -2., 3])
x[x < 0] += 20
print(x)

x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
print(rowsum)
print(x[rowsum <= 2, :])

## Broadcasting

One of the best things about numpy is broadcasting. If two numpy arrays have compatible shape then boolean operations like ```*```, ```+```, ```-```, ```\```, ```>``` etc. can be broadcast elementwise.

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
print(a * b)
print(a + b)
print(a / b)
print(a - b)
print(a > b)

In [ ]:
# broadcastable array with different shape
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
print(a.shape, b.shape)
print(a + b)

# non broadcastable array with incompatible shapes
b = np.array([1.0, 2.0, 3.0, 4.0])
print(a.shape, b.shape)
print(a + b)

In [ ]:
# to add a and b we need to reshape b so that the addition operation is boradcast over the first dimension
b=b.reshape(-1, 1)
print(a.shape, b.shape)
print(a+b)

## Advanced tutorials

For more advanced tutorials see: (https://numpy.org/numpy-tutorials/)

## Basic linear algebra with numpy

These are indended to be exercises, please compute the results by hand and then uncomment the print statement to see if you were correct or not. 

In [ ]:
import numpy.linalg as lin

In [ ]:
# dot product - remeber the dot product is an elementwise multiplication and then sum of the results
#print(np.dot(3, 4))
a = [2,3,1,4]
b = [0,1,3,1]
#print(np.dot(a, b))
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
#print(np.dot(a,b))

In [ ]:
# inner product - this is defined only for vectors, remember this is the same as the dot product
a = [2,3,1,4]
b = [0,1,3,1]
#print(np.inner(a, b))
# outer product - this defined only for vectors, this constructs a matrix
#print(np.outer(a, b))

In [ ]:
# matrix matrix multiplication
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
#print(np.matmul(a, b))
# matrix vector multiplication
a = np.array([[1, 0],
              [0, 1]])
b = np.array([1, 2])
#print(np.matmul(a, b))

In [ ]:
# matrix transpose
a = np.array([[1, 3],
       [2, 4]])
#print(np.transpose(a))

In [ ]:
# matrix determinant
a = np.array([[1, 3],
       [2, 4]])
#print(lin.det(a))

In [ ]:
# matrix inverse
a = np.array([[1, 3],
       [2, 4]])
#print(lin.inv(a))

In [ ]:
# eigen values and eigen vectors
a = np.array([[1, 3],
       [2, 4]])
eigenvalues, eigenvectors = lin.eig(a)
#print(eigenvalues)
#print(eigenvectors)

In [ ]:
# when the matrix is diagonal the eigenvalues and eigenvectors are easy to compute
d = np.diag((1, 2, 3))
print(d)
eigenvalues, eigenvectors = lin.eig(d)
#print(eigenvalues)
#print(eigenvectors)